name: Generate-SBOM
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        echo "Debug ======> master"
    - name: Tar Assets
      run: |
        echo 123 >> helloworld222
    - name: Upload Release Assets
      uses: AButler/upload-release-assets@v3.0
      with:
        files: helloworld222
        repo-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        release-tag: ${{ inputs.tag }}