name: Release - Sprint

on:
  workflow_dispatch:
    inputs:

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        branch_tag: ['master:master-head-20240818']

    steps:
    - name: Setup Git
      run: |
        gh auth setup-git

    - uses: anchore/sbom-action/download-syft@v0.17.0

    - run: |
        git config --global user.email "dko@suse.com"
        git config --global user.name "David Ko"

    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: innobead/renote
        ref: main
        path: renote
    - run: cargo install --path ./renote

    - id: var
      name: Get branch, tag, milestone
      run: |
        IFS=':' read -ra tokens <<< "${{ matrix.branch_tag }}"
        branch="${tokens[0]}"
        tag="${tokens[1]}-dev-$(date '+%Y%m%d')"
        milestone="${tokens[2]}"

        if [ -z "${tokens[2]}" ]; then milestone="${tokens[1]}" ; fi

        echo "branch=${branch}" >> $GITHUB_OUTPUT
        echo "tag=${tag}" >> $GITHUB_OUTPUT
        echo "milestone=${milestone}" >> $GITHUB_OUTPUT

        cat <<EOF
        branch=${branch}
        tag=${tag}
        milestone=${milestone}
        EOF

        - id: artifact
        name: Collect artifacts
        run: |
          ./scripts/collect-artifacts.sh longhorn charts

    - id: tag
      name: Create a tag for each release repo
      run: |
        renote tag \
          --owner derekbit \
          --branch ${{ steps.var.outputs.branch }} \
          --tag ${{ steps.var.outputs.tag }} \
          --repos longhorn-manager
